# .streamlit/secrets.toml

SUPABASE_URL = "https://fbmikjyyculnpmkyyurc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZibWlranl5Y3VsbnBta3l5dXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTg3NzQsImV4cCI6MjA3MDU3NDc3NH0.OFKJIoNe9dLMBH1EoKey8tZ03RXGerYdaDxJsTZiYls"